name: Fake packaging

on: [push]

jobs:
  lala:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: main.py